### ISSUE TITLE
<Card/> component looks broken in storybook

### ISSUE THREAD

**Issue by nktssh** [wix/wix-ui-tpa#103]
https://wix-wix-ui-tpa.surge.sh/?path=/story/components--card

**Comment by jonathanadler** [comment]
@nktssh Can you describe what seems to be broken?
It might have been a momentary issue.

**Comment by nktssh** [comment]
<img width="1285" alt="Crs looks broken" src="https://user-images.githubusercontent.com/1872256/61062785-82575a80-a407-11e9-92ec-5c56063caa04.png">

**Comment by jonathanadler** [comment]
@nktssh Does this persist if you refresh?

**Comment by nktssh** [comment]
@jonathanadler yes

**Comment by jonathanadler** [comment]
@nktssh 
I wasn't able to reproduce this, however, we are aware this is happening.
It seems to be a race condition that's causing this, and not a bug in the components.
We will try to find and fix the root cause of this.
Thanks!
