### ISSUE TITLE
Update Avatar sizes

### ISSUE THREAD

**Issue by jonathanadler** [wix/wix-ui-tpa#397]
We have an `Avatar` component:
https://bo.wix.com/pages/wix-ui-tpa/?path=/story/components--avatar

As you can see, It has 4 different sizes.

We need to adjust to the sizes as defined here:
https://zeroheight.com/7sjjzhgo2/p/723c40-01-elements/t/5d36

Note that we don't want to break the component's API, and our consumers apps.

If there's a conflict we might need to consider using a "feature-toggle" in the form of an `upgrade` prop (as in the `Button` Component)

**Comment by sivanharel** [comment]
Done
