### ISSUE TITLE
ActionsMenuLayout A11Y fixes

### ISSUE THREAD

**Issue by jonathanadler** [wix/wix-ui-tpa#401]
## ActionsMenu Item
See ws example here: https://www.w3.org/TR/2016/WD-wai-aria-practices-1.1-20161214/examples/menu-button/menu-button-1/menu-button-1.html

* should expose a `focus` method - internally will have a ref to the button and invoke the buttons focus (should it also be focusable if not clickable?)
* onClick should also fire when focused on an item and pressed `space` or `enter`

## ActionsMenu
* `aria-labelledby` and `aria-label` props
* navigation with keyboard arrows

**Comment by jonathanadler** [comment]
updated the spec

**Comment by bordi** [comment]
https://github.com/wix/wix-ui-tpa/pull/406
