### ISSUE TITLE
(Docs) Spinner settings panel code shows [object Module]

### ISSUE THREAD

**Issue by povilastwix** [wix/wix-ui-tpa#445]
Spinner code in settings pannel is not displayed properly.
URL: https://bo.wix.com/pages/wix-ui-tpa/?activeTab=Settings%20Panel&path=%2Fstory%2Fcomponents--spinner
![image](https://user-images.githubusercontent.com/70896490/96971570-fa269700-151d-11eb-819f-c2baa6832cdb.png)

**Comment by jonathanadler** [comment]
Seems to be resolved
